### Module to communicate with the database

import sqlite3


class Database_Connection:
    def __init__(self):
        self.connection = sqlite3.connect('brews.db')
        self.cursor = self.connection.cursor()

    def commit(self):
        self.connection.commit()

    def open_coffees(self):
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS coffees (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        BRAND varchar2 NOT NULL,
        NAME varchar2 NOT NULL,
        DESCRIPTION varchar2,
        COMMENT varchar2,
        AI COMMENT varchar2,
        ROAST varchar2,
        ORIGIN varchar2
        )''')  # User provides all the data except AI Comment which will be auto-generated by Gemini free-tier

    def open_brews(self):
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS brews (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        DATE varchar2 NOT NULL,
        TIME varchar2 NOT NULL,
        TIME_OF_BREWING INTEGER,
        GRINDER_SETTINGS varchar2 NOT NULL,
        COFFEE INTEGER NOT NULL,
        TASTE INTEGER NOT NULL,
        SWEET INTEGER NOT NULL,
        ACIDITY INTEGER NOT NULL,
        BITTER INTEGER NOT NULL,
        FOREIGN KEY(COFFEE) REFERENCES coffees(ID)
        )''')  # Date and Time logs automatically, time_of_brewing, grinder_set, coffee - user , ratings on 1-10 scale

    def start_program(self):
        self.open_brews()
        self.open_coffees()
        self.commit()
        print("Databases opened")

    def add_coffee(self, brand, name, description, comment, roast, origin):  # Used to add new coffee
        self.cursor.execute(f''' INSERT INTO COFFEES (BRAND, NAME, DESCRIPTION, COMMENT, ROAST, ORIGIN)
        VALUES ({brand}, {name}, {description}, {comment}, {roast}, {origin}
        )''')

        self.commit()

    def update_coffee(self, id, brand, name, description, comment, roast, origin):
        self.cursor.execute(f''' UPDATE COFFEES
        SET BRAND = {brand},
        NAME = {name},
        DESCRIPTION = {description},
        COMMENT = {comment},
        ROAST = {roast},
        ORIGIN = {origin}
        WHERE ID = {id}
        ''')
        self.commit()

    def add_brews(self, date, time, time_of_brew, grinder_settings, coffee, taste, sweet, acidity, bitter):  # Used to add new brew
        self.cursor.execute(f'''INSERT INTO BREWS (DATE, TIME, TIME_OF_BREWING, GRINDER_SETTINGS, COFFEE, TASTE, SWEET, ACIDITY, BITTER)
        VALUES ({date}, {time}, {time_of_brew}, {grinder_settings}, {coffee}, {taste}, {sweet}, {acidity}, {bitter}
        )''')

        self.commit()

    def update_brews(self, id, date, time, time_of_brew, grinder_settings, coffee, taste, sweet, acidity, bitter):
        self.cursor.execute(f'''UPDATE BREWS
        SET DATE = {date},
        TIME = {time},
        TIME_OF_BREWING = {time_of_brew},
        GRINDER_SETTINGS = {grinder_settings},
        COFFEE = {coffee},
        TASTE = {taste},
        SWEET = {sweet},
        ACIDITY = {acidity},
        BITTER = {bitter}
        WHERE ID = {id}
        ''')


x = Database_Connection()
x.start_program()
