### Module to communicate with the database

import sqlite3


class Database_Connection:
    def __init__(self):
        self.connection = sqlite3.connect('brews.db')
        self.cursor = self.connection.cursor()

    def commit(self):
        self.connection.commit()

    def open_brews(self):
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS brews (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        DATE varchar2 NOT NULL,
        TIME varchar2 NOT NULL,
        TIME_OF_BREWING INTEGER,
        GRINDER_SETTINGS varchar2 NOT NULL,
        coffee INTEGER,
        TASTE INTEGER NOT NULL,
        SWEET INTEGER NOT NULL,
        ACITY INTEGER NOT NULL,
        BITTER INTEGER NOT NULL
        )''')  # Date and Time logs automatically, time_of_brewing, grinder_set, coffee - user , ratings on 1-10 scale

    def open_coffees(self):
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS coffees (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        BRANDING varchar2 NOT NULL,
        NAME varchar2 NOT NULL,
        DESCRIPTION varchar2,
        COMMENT varchar2,
        AI COMMENT varchar2,
        ROAST varchar2,
        ORIGIN varchar2
        )''')  # User provides all the data except AI Comment which will be auto-generated by Gemini free-tier

    def start_program(self):
        self.open_brews()
        self.open_coffees()
        self.commit()
        print("Databases opened")


x = Database_Connection()
x.start_program()
