### Module to communicate with the database

import sqlite3


class DatabaseConnection:
    def __init__(self):
        self.connection = sqlite3.connect('brews.db')
        self.cursor = self.connection.cursor()

    def commit(self):
        self.connection.commit()

    def open_table_coffees(self):
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS coffees (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        BRAND TEXT NOT NULL,
        NAME TEXT NOT NULL,
        DESCRIPTION TEXT,
        COMMENT TEXT,
        AI_COMMENT TEXT,
        ROAST TEXT,
        ORIGIN TEXT
        )''')  # User provides all the data except AI Comment which will be auto-generated by Gemini free-tier

    def open_table_brews(self):
        self.cursor.execute('''CREATE TABLE IF NOT EXISTS brews (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        DATE DATE NOT NULL,
        TIME TIME NOT NULL,
        TIME_OF_BREWING INTEGER,
        GRINDER_SETTINGS TEXT NOT NULL,
        COFFEE INTEGER NOT NULL,
        TASTE INTEGER NOT NULL,
        SWEET INTEGER NOT NULL,
        ACIDITY INTEGER NOT NULL,
        BITTER INTEGER NOT NULL,
        FOREIGN KEY(COFFEE) REFERENCES coffees(ID)
        )''')  # Date and Time logs automatically, time_of_brewing, grinder_set, coffee - user , ratings on 1-10 scale

    def start_program(self):
        self.open_table_brews()
        self.open_table_coffees()
        self.commit()
        print("Databases opened")

    def add_coffee(self, brand, name, description, comment, roast, origin):  # Used to add new coffee
        self.cursor.execute(''' INSERT INTO COFFEES (BRAND, NAME, DESCRIPTION, COMMENT, ROAST, ORIGIN)
        VALUES (?,?,?,?,?,?)''', (brand, name, description, comment, roast, origin))

        self.commit()

    def update_coffee(self, id, brand, name, description, comment, roast, origin):
        self.cursor.execute(''' UPDATE COFFEES
        SET BRAND = ?,
        NAME = ?,
        DESCRIPTION = ?,
        COMMENT = ?,
        ROAST = ?,
        ORIGIN = ?
        WHERE ID = ?
        ''', (brand, name, description, comment, roast, origin, id))

        self.commit()

    def add_brews(self, date, time, time_of_brew, grinder_settings, coffee, taste, sweet, acidity,
                  bitter):  # Used to add new brew
        self.cursor.execute('''INSERT INTO BREWS (DATE, TIME, TIME_OF_BREWING, GRINDER_SETTINGS, COFFEE, TASTE, SWEET, ACIDITY, BITTER)
        VALUES (?,?,?,?,?,?,?,?,?
        )''', (date, time, time_of_brew, grinder_settings, coffee, taste, sweet, acidity, bitter))

        self.commit()

    def update_brews(self, id, date, time, time_of_brew, grinder_settings, coffee, taste, sweet, acidity, bitter):
        self.cursor.execute('''UPDATE BREWS
        SET DATE = ?,
        TIME = ?,
        TIME_OF_BREWING = ?,
        GRINDER_SETTINGS = ?,
        COFFEE = ?,
        TASTE = ?,
        SWEET = ?,
        ACIDITY = ?,
        BITTER = ?
        WHERE ID = ?
        ''', (date, time, time_of_brew, grinder_settings, coffee, taste, sweet, acidity, bitter, id))

        self.commit()


x = DatabaseConnection()
x.start_program()
